# Generated by Django 6.0.4 on 2026-05-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('Impact', 'Impact'), ('Training', 'Training'), ('Farming', 'Farming'), ('Wellness', 'Wellness')], max_length=50)),
                ('description', models.CharField(blank=True, help_text='e.g., Location or short detail', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
