# Generated by Django 6.0.4 on 2026-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(help_text='e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ')),
                ('category', models.CharField(choices=[('Training', 'Training'), ('Economy', 'Economy'), ('Farming', 'Farming'), ('Wellness', 'Wellness')], max_length=50)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('duration', models.CharField(help_text='e.g., 15:30', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
