# Generated by Django 6.0.4 on 2026-05-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Optional: Upload a custom thumbnail. If blank, YouTube's thumbnail will be used.", null=True, upload_to='video_thumbnails/'),
        ),
    ]
