# Generated by Django 6.0.4 on 2026-05-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Manual', 'Manual'), ('Tracker', 'Tracker'), ('Technical', 'Technical'), ('Guide', 'Guide')], max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(help_text='Cover image for the PDF', upload_to='pdf_thumbnails/')),
                ('pdf_file', models.FileField(upload_to='pdf_guides/')),
                ('pages', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
