# Generated by Django 6.0.4 on 2026-05-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pdfguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Workshop', 'Workshop'), ('Finance', 'Finance'), ('Farming', 'Farming'), ('Health', 'Health'), ('Community', 'Community')], max_length=50)),
                ('presenter', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(help_text='Cover image for the presentation', upload_to='slide_thumbnails/')),
                ('slide_file', models.FileField(help_text='Upload PPTX or PDF slides', upload_to='slides/')),
                ('slides_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
