# Generated by Django 5.2.5 on 2026-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_pdfguide_course_slide_course_video_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSupportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(help_text='Service image URL (pexels/your CDN/etc.)', max_length=500)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(default='info@be2sahobe.rw', max_length=254)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
