# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_homepage_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.CharField(default='Kigali, Rwanda', max_length=255)),
                ('contact_phone', models.CharField(default='+250 788 487 127', max_length=30)),
                ('contact_email', models.EmailField(default='hello@be2sahobe.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='250783558316', help_text='International format without +, e.g. 250783558316', max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('footer_tagline', models.TextField(default='A digital ecosystem for holistic family living — integrating education, support, economic empowerment, and community across Africa.')),
                ('footer_copyright', models.CharField(default="© 2026 BE2SAHOBE LTD — We don't just teach, we help families IMPLEMENT change.", max_length=255)),
                ('home_hero_badge', models.CharField(default='Digital Ecosystem for Families', max_length=120)),
                ('home_hero_title_learn', models.CharField(default='Learn.', max_length=40)),
                ('home_hero_title_grow', models.CharField(default='Grow.', max_length=40)),
                ('home_hero_title_rest', models.CharField(default='Thrive. Together.', max_length=80)),
                ('home_hero_subtitle', models.TextField(default='A transformative digital ecosystem empowering families through holistic living — integrating health, education, spiritual growth, economic empowerment, and sustainable community development.')),
                ('home_cta_primary_text', models.CharField(default='Explore Learning Programs', max_length=80)),
                ('home_cta_primary_url', models.CharField(default='#courses', max_length=200)),
                ('home_cta_secondary_text', models.CharField(default='Access Professional Support', max_length=80)),
                ('home_cta_secondary_url', models.CharField(default='#services', max_length=200)),
                ('home_stat_1_num', models.CharField(default='5', max_length=20)),
                ('home_stat_1_label', models.CharField(default='Holistic Living Pillars', max_length=80)),
                ('home_stat_2_num', models.CharField(default='1', max_length=20)),
                ('home_stat_2_label', models.CharField(default='Integrated Family Ecosystem', max_length=80)),
                ('home_stat_3_num', models.CharField(default='24/7', max_length=20)),
                ('home_stat_3_label', models.CharField(default='Accessible Digital Support', max_length=80)),
                ('home_card_title', models.CharField(default='Your Journey Starts Here', max_length=120)),
                ('home_card_subtitle', models.CharField(default='Education → Support → Action', max_length=120)),
                ('home_card_item_1', models.CharField(default='Holistic Education & Digital Learning Resources', max_length=200)),
                ('home_card_item_2', models.CharField(default='Family Counseling, Mentorship & Christian Guidance', max_length=200)),
                ('home_card_item_3', models.CharField(default='Career Development & Economic Empowerment Programs', max_length=200)),
                ('home_card_item_4', models.CharField(default='Trusted Professional Consultancy & Community Support Services', max_length=200)),
                ('home_card_button_text', models.CharField(default='Start Your Journey Today', max_length=80)),
                ('about_hero_badge', models.CharField(default='Who We Are', max_length=80)),
                ('about_hero_title', models.CharField(default='Empowering Families for', max_length=200)),
                ('about_hero_title_highlight', models.CharField(default='Holistic Transformation', max_length=120)),
                ('about_hero_subtitle', models.TextField(default='BE2SAHOBE LTD and MIFAA/NGoP work in synergy to provide Rwandan families with the tools, knowledge, and support needed to thrive in the modern world while staying rooted in community values.')),
                ('about_vision_title', models.CharField(default='Our Vision', max_length=80)),
                ('about_vision_text', models.TextField(default='To be the leading digital ecosystem that empowers every Rwandan family to achieve holistic transformation and lasting prosperity, creating a future where every household is healthy, wealthy, and wise.')),
                ('about_mission_title', models.CharField(default='Our Mission', max_length=80)),
                ('about_mission_text', models.TextField(default='To provide structured education, professional counseling, and practical economic tools that enable families to thrive across five key pillars: Body, Economy, Mind, Spirit, and Environment, through innovative digital platforms and community outreach.')),
                ('about_history_badge', models.CharField(default='Background & History', max_length=80)),
                ('about_history_title', models.CharField(default='Our Journey', max_length=120)),
                ('about_history_paragraph_1', models.TextField(default='BE2SAHOBE LTD was established with a clear mandate: to bridge the gap between theoretical knowledge and practical action in family development. Recognizing that modern families face complex challenges, we developed a "Holistic Living" framework that addresses the body, mind, spirit, economy, and environment as an interconnected whole.')),
                ('about_history_paragraph_2', models.TextField(default='In partnership with MIFAA/NGoP, our non-profit arm, we have expanded our reach to the most vulnerable communities, providing not just training, but the essential support systems like the IKIGEGA savings program and professional counseling.')),
                ('about_history_image', models.ImageField(blank=True, null=True, upload_to='site/about/')),
                ('about_history_image_url', models.URLField(blank=True, default='https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=800', help_text='Used when no uploaded image is set', max_length=500)),
                ('about_history_card_title', models.CharField(default='Founded on Values', max_length=120)),
                ('about_history_card_text', models.CharField(default='Blending tradition with digital innovation for family growth.', max_length=255)),
                ('about_cta_title', models.CharField(default='Join Our Community', max_length=120)),
                ('about_cta_text', models.TextField(default='Be part of a movement that is redefining family life in Rwanda. Start your journey toward holistic living today.')),
                ('about_cta_button_text', models.CharField(default='Get Started Now', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
