# Generated by Django 5.2.5 on 2026-05-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_dynamic_categories_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionalsupportservice',
            options={'ordering': ['homepage_order', 'order', '-created_at']},
        ),
        migrations.AlterField(
            model_name='professionalsupportservice',
            name='image_url',
            field=models.URLField(help_text='Service image URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_cta_primary_url',
            field=models.CharField(default='#learning', max_length=200),
        ),
    ]
